/**
 * Loads the current banner data from the static JSON generated by GitHub Actions.
 * The file lives at /wish-counter/banners-current.json (same origin — no CORS).
 * Module-level cache: fetched once per page load.
 */

const BASE_PATH = import.meta.env.BASE_URL ?? '/wish-counter/';

let _cache = null;   // { fetchedAt, banners } | false (fetch failed)
let _promise = null; // in-flight request

/**
 * Returns the parsed banners object, or null if unavailable.
 * Shape: { character: { featured, endDate }, weapon: { featuredWeapons, endDate }, ... }
 */
export async function getCurrentBanners() {
  if (_cache !== null) return _cache || null;
  if (_promise) return _promise;

  _promise = fetch(`${BASE_PATH}banners-current.json`, {
    signal: AbortSignal.timeout(8000),
  })
    .then((r) => {
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return r.json();
    })
    .then((data) => {
      _cache = data?.banners ?? {};
      return _cache;
    })
    .catch(() => {
      _cache = false;
      return null;
    })
    .finally(() => {
      _promise = null;
    });

  return _promise;
}

/**
 * Returns true if the stored banner metadata looks stale:
 * - endDate is missing, or
 * - endDate is in the past
 */
export function isBannerStale(metadata) {
  if (!metadata) return true;
  const { endDate } = metadata;
  if (!endDate) return true;
  return new Date(endDate) < new Date();
}

let _upcomingCache = null;
let _upcomingPromise = null;

/**
 * Merges upcoming banners from two sources:
 * 1. `banners-current.json#upcoming` — future phases detected by GitHub Actions from paimon.moe
 * 2. `banners-upcoming.json` — manually curated leaks/confirmed-but-not-yet-on-paimon banners
 *
 * Returns a deduplicated, sorted array of upcoming banner entries.
 */
export async function getUpcomingBanners() {
  if (_upcomingCache !== null) return _upcomingCache;
  if (_upcomingPromise) return _upcomingPromise;

  _upcomingPromise = Promise.allSettled([
    fetch(`${BASE_PATH}banners-current.json`, { signal: AbortSignal.timeout(8000) })
      .then((r) => r.ok ? r.json() : null)
      .then((d) => d?.upcoming ?? []),
    fetch(`${BASE_PATH}banners-upcoming.json`, { signal: AbortSignal.timeout(8000) })
      .then((r) => r.ok ? r.json() : [])
      .catch(() => []),
  ])
    .then(([autoResult, manualResult]) => {
      const auto   = autoResult.status   === 'fulfilled' ? (autoResult.value   ?? []) : [];
      const manual = manualResult.status === 'fulfilled' ? (manualResult.value ?? []) : [];

      // Merge — deduplicate by version+bannerKey+featured
      const seen = new Set();
      const merged = [];
      for (const entry of [...auto, ...manual]) {
        const key = `${entry.version}-${entry.bannerKey}-${entry.featured}`;
        if (!seen.has(key)) {
          seen.add(key);
          merged.push(entry);
        }
      }

      // Sort: official first, then by startDate ascending (nulls last)
      merged.sort((a, b) => {
        if (a.confidence !== b.confidence) return a.confidence === 'officiel' ? -1 : 1;
        const aD = a.startDate ? new Date(a.startDate).getTime() : Infinity;
        const bD = b.startDate ? new Date(b.startDate).getTime() : Infinity;
        return aD - bD;
      });

      _upcomingCache = merged;
      return merged;
    })
    .finally(() => { _upcomingPromise = null; });

  return _upcomingPromise;
}
