/**
 * Loads the current banner data from the static JSON generated by GitHub Actions.
 * The file lives at /wish-counter/banners-current.json (same origin — no CORS).
 * Module-level cache: fetched once per page load.
 */

const BASE_PATH = import.meta.env.BASE_URL ?? '/wish-counter/';

let _cache = null;   // { fetchedAt, banners } | false (fetch failed)
let _promise = null; // in-flight request

/**
 * Returns the parsed banners object, or null if unavailable.
 * Shape: { character: { featured, endDate }, weapon: { featuredWeapons, endDate }, ... }
 */
export async function getCurrentBanners() {
  if (_cache !== null) return _cache || null;
  if (_promise) return _promise;

  _promise = fetch(`${BASE_PATH}banners-current.json`, {
    signal: AbortSignal.timeout(8000),
  })
    .then((r) => {
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return r.json();
    })
    .then((data) => {
      _cache = data?.banners ?? {};
      return _cache;
    })
    .catch(() => {
      _cache = false;
      return null;
    })
    .finally(() => {
      _promise = null;
    });

  return _promise;
}

/**
 * Returns true if the stored banner metadata looks stale:
 * - endDate is missing, or
 * - endDate is in the past
 */
export function isBannerStale(metadata) {
  if (!metadata) return true;
  const { endDate } = metadata;
  if (!endDate) return true;
  return new Date(endDate) < new Date();
}
